### ISSUE TITLE
proper naming

### ISSUE THREAD

**Issue by flying-sheep** [PMBio/scLVM#14]
It’s bad style to name things in `lowerCamelCase`

Also classes have to be `UpperCamelCase`

As a python user I expect to do

``` py
# aah, I’m importing a class from a module, sure!
from sclvm import ScLVM
```

not

``` py
# huh, “scLVM” twice? the first one is a module, and the second one?
from scLVM.core import scLVM
```

**Comment by flophys** [comment]
thanks for your comment, Phil. Will change this to be more pythonic in the next release.
