### ISSUE TITLE
IndexError: index XX is out of bounds for axis 0 with size XX of scLVM/core.py

### ISSUE THREAD

**Issue by Japrin** [PMBio/scLVM#16]
Hi,

the code around 204 line of scLVM/core.py :

```
if not _conv:
        var[count,-2] = SP.maximum(0,y.var()-tech_noise[ids])
        var[count,-1] = tech_noise[ids]
        count+=1;
        if self.geneID is not None: geneID[count] = self.geneID[ids]
        continue
```

I think `count+=1;` should be put after `if self.geneID is not None:    geneID[count] = self.geneID[ids]`. Otherwise when I call the function varianceDecomposition() with i0 and i1 setting as, for example,  100 and 150, the  out of bounds error occur frequently if ids reach i1.
Also I don't know why do the assignment `geneID[count] = self.geneID[ids]`  only when _conv is False, rather than assigning the geneID for every ids. 

Thanks!

**Comment by flophys** [comment]
good catch, thank you. fixed.
