### ISSUE TITLE
  'module' object has no attribute 'CFixedCF'

### ISSUE THREAD

**Issue by jkleinj** [PMBio/scLVM#17]
Dear Authors,

I am running the vignette
https://github.com/PMBio/scLVM/blob/master/R/tutorials/scLVM_vignette.Rmd

on the current (cloned) version of scLVM
https://github.com/PMBio/scLVM/blob/master/R/scLVM_0.99.2.tar.gz.

In the section 'Fitting multiple factors', the line
% th2 = fitFactor(sclvmMult, idx = idx_Th2, XKnown = Xcc, k = 1, interaction=TRUE)
returns an error message of the type
%  'module' object has no attribute 'CFixedCF'.

Do you have an explanation and possibly a solution for that?

Thanks,
  Jens

**Comment by arthuryxt** [comment]
Dear Authors,

I am also stuck there. Could you fix it?

Thanks,
Arthur

**Comment by emerygoossens** [comment]
I cannot seem to get past this part either. I am having trouble including additional covariates when using the fitFactor() function. In particular, when including a binary treatment/control vector, I get the following error.

CellCycle = fitFactor(sclvm,geneSet = ens_ids_cc,XKnown = cell_binary, k=1,use_ard = F)

Error in python.exec(paste("X,K,Kint,varGPLVM_ARD = ", objName, ".fitFactor(idx=idx, X0=X0, k=k,standardize=standardize, use_ard=use_ard, interaction=interaction, initMethod=initMethod)",  : 
  ufunc 'divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

**Comment by jshaik1979** [comment]
Same issue, has this been fixed? This is where it fails for me:
th2 = fitFactor(sclvmMult, idx = idx_Th2, XKnown = Xcc, k = 1, interaction=TRUE)
