### ISSUE TITLE
Calculation of squared coefficient of variation

### ISSUE THREAD

**Issue by Rashika40** [PMBio/scLVM#2]
Following is the snippet of R code for calculation of squared coefficient of variation for endogenous genes and ERCC spike - ins:
# normalized counts (brennecke)

meansMmus <- rowMeans( nCountsMmus )
varsMmus <- rowVars( nCountsMmus )
cv2Mmus <- varsMmus / meansMmus^2

meansERCC <- rowMeans( nCountsERCC )
varsERCC <- rowVars( nCountsERCC )
cv2ERCC <- varsERCC / meansERCC^2

But squared coefficient of variation should be calculated as (variance/means)^2 and not variance/mean^2. 

Is there a mistake in the code or am I missing something?

**Comment by flophys** [comment]
Hi Rashika, 

the CV is defined as standard deviation over mean, so squared CV is squared standard deviation over squared mean which is variance over squared mean....
http://en.wikipedia.org/wiki/Coefficient_of_variation

cheers, 
florian

**Comment by Rashika40** [comment]
Hi Florian

Sorry, I confused variance for standard deviation. Thanks a lot!
