### ISSUE TITLE
core.py limix version check triggers automatic failure state, attempts to load nonexistent package

### ISSUE THREAD

**Issue by ambrosejcarr** [PMBio/scLVM#25]
I'm trying to get scLVM working and am running into some installation problems. 

Below I reference code in `core.py`:

```
import limix
try:
	limix.__version__
	if versiontuple(limix.__version__)>versiontuple('0.7.3'):
		import limix.deprecated as limix

except:
	import limix.deprecated as limix
```

`versiontuple` is not defined in local scope during import, so the except loop is automatically triggered by the `NameError` generated when `versiontuple` is referenced. As a result, `limix.deprecated` is imported constitutively. 

However, many versions of `limix` do not have a `deprecated` package and it is not trivial to find the correct version of the package that will work with this code. 

Suggest hard coding the correct versions into `requirements.txt` or `setup.py` so that a valid version is required for installation.

**Comment by Shians** [comment]
I referred to this in a comment inside #15, as far as I can tell the limix version associated with PMBio still has deprecated while the new one set up under the account limix does not.

**Comment by flophys** [comment]
This was due to a major upgrade of limix. I have updated scLVM to work with the latest release of limix - thanks for catching this and sorry for the delayed fix.

**Comment by ambrosejcarr** [comment]
Perfect, thanks very much!
