### ISSUE TITLE
Use of scLVM for single cell data under multiple conditions

### ISSUE THREAD

**Issue by yangqi-su** [PMBio/scLVM#29]
I wish to remove the cell cycle effect for my data which consists of single cell RNAseq for cells under different conditions. I waas wondering which of the following methods made more sense: 
1. Removing the cell cycle effect using the entire data as input
2. Removing the effect for each condition and combine the data that has the cell cycle effect regressed out after.
Thank you.

**Comment by pfaucon** [comment]
I would suggest asking on a more active site for bioinformatics questions.  My feeling though is that case 1 will give you more treatable results. Case 2 might be better at removing the cell cycle noise but may also emphasize the differences from other conditions.  

Data processing is fairly cheap though, I would run it both ways but with less trust for the output of the second
