### ISSUE TITLE
error message when load limix in R

### ISSUE THREAD

**Issue by xiangzhou** [PMBio/scLVM#5]
I was trying to use scLVM but I got an error message. I was following the instruction at https://github.com/PMBio/scLVM/blob/master/R/tutorials/scLVMr_demo_nospikeins.Rmd. Below is what I did and the error message I got:
1. I installed LIMIX by downloading the limix-master from github. I used the setup.py to install it: python setup.py install --user
2. I installed scLVM R package, by downloading the file from (https://github.com/PMBio/scLVM/tree/master/R). I installed it in the terminal: R CMD INSTALL scLVM_0.99.2.tar.gz -l ../R/x86_64-pc-linux-gnu-library/2.10/
3. I then opened R, and was able to load scLVM by library(scLVM). However, I was not able to run configLimix(limix_path). I found two possible limix_path:
   ./src/interfaces/python or ./build/temp.linux-x86_64-2.7/src/interfaces/python, but both of these paths gave me the same error message:

> configLimix(limix_path)
>   File "<string>", line 3
>     except Exception as e:_r_error = e.__str__()
>          ^
> IndentationError: expected an indented block
> Warning message:
> In file(con, "r") :
>   file("") only supports open = "w+" and open = "w+b": using the former

Please let me know how I would be able to use scLVM. Thanks.

**Comment by skiaphrene** [comment]
Hi xiandzhou,

I found that this issue was due to a file path problem in the configLimix() function. I worked around by using this configLimix2() function instead of configLimix():

```
configLimix2 <- function (limix_path) {
  python.assign("limix_path", limix_path)
  python.exec("sys.path.append(limix_path)")
  python.load(system.file("pysrc", "init_data.py", package = "scLVM"))
  # in the original configLimix it says "py" instead of "pysrc"
}
```

Hope this helps,

-- Alex

**Comment by flophys** [comment]
fixed, thanks Alex!
