### ISSUE TITLE
error message when loading scLVM package

### ISSUE THREAD

**Issue by matahi** [PMBio/scLVM#6]
Hello, I followed the installation steps for the scLVM R package but I run into the following error message when doing R CMD INSTALL scLVM:

Error : .onAttach failed in attachNamespace() for 'scLVM', details:
  call: if (pmatch("No module named ", e[[1]]) == 1) {
  error: missing value where TRUE/FALSE needed

Do you have any knowledge how to fix this error?

Thanks

**Comment by flophys** [comment]
Hi, 

please follow our troubleshooting instructions, this usually solves this problem:

https://github.com/PMBio/scLVM/wiki/Troubleshooting

Thanks

**Comment by lrodda** [comment]
Hi, 
I am having the same issue. I followed the installation instructions (https://github.com/PMBio/scLVM/wiki/Installation) to the point of installing rPython (the current homebrew version that downloaded is 2.7.12 as of this writing) and downloaded the scLVM tarball (which is now scLVM_0.99.2.tar.gz). However, when I run:

$ R CMD INSTALL scLVM_0.99.2.tar.gz 

Error : .onAttach failed in attachNamespace() for 'scLVM', details:
  call: if (pmatch("No module named ", e[[1]]) == 1) {
  error: missing value where TRUE/FALSE needed
Error: loading failed
Execution halted
ERROR: loading failed

Following the suggestion above I ran the troubleshooting to make sure I was running the homebrew version of python and found that R sees only the Mac OSX default:

2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

but by terminal: python --version 
returns Python 2.7.12

Both are 2.7, but not exactly the same could this be the problem? I've reinstalled both after running $export RPYTHON_PYTHON_VERSION=2.7.12, but nothing changed. Do I have to set the environmental variable somewhere specific? In the bash.rc?

(>python.exec("import limix; limix.**version**") runs on R fine.)

$ which python | xargs ls -l 
lrwxr-xr-x  1 lrodda  admin  34 Aug 26 11:42 /usr/local/bin/python -> ../Cellar/python/2.7.12/bin/python

I also tried installing scLVM via Rstudio and:

> library("scLVM", lib.loc="/Library/Frameworks/R.framework/Versions/3.3/Resources/library")
> RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
> RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
> Error : .onAttach failed in attachNamespace() for 'scLVM', details:
>   call: if (pmatch("No module named ", e[[1]]) == 1) {
>   error: missing value where TRUE/FALSE needed
> Error: package or namespace load failed for ‘scLVM’

I've updated and reinstalled numpy with no change.

Any help would be greatly appreciated.
Thank you!

**Comment by flophys** [comment]
HI Lauren, 

hm, yes, the is caused by the 2 python versions - it’s an rPython issue, the author of that package outlined a possible solution here: https://cran.r-project.org/web/packages/rPython/INSTALL https://cran.r-project.org/web/packages/rPython/INSTALL

But I’m not sure if it works with only differences in the minor version of python..there is no need to set the environmental variable anywhere specific, but I’ll have think again.

florian

**Comment by lrodda** [comment]
Hi Florian,
I fixed it! The key was uninstalling rPython AND scLVM (even though it never technically installed it was available as a package in RStudio) and then setting the environmental variable and reinstalling. Obvious in retrospect. Thank you for the other fix you just posted for this error:

> Error in python.exec(paste(objName, " = scLVM(Y,geneID=geneID,tech_noise=tech_noise)",  :
>   name 'scLVM' is not defined
> 
> python.load(system.file("pysrc","init_data.py",package = "scLVM"))

fixed the issue.

Now to actually analyze my data!

Thank you for your help,
Lauren

**Comment by arthuryxt** [comment]
@lrodda I got the same problem (two versions of python on OSX), and I tried to follow your suggestion but failed. Could you please take a look at mine steps and point out my mistakes?

$1$ in terminal:
export RPYTHON_PYTHON_VERSION=2.7.12

$2$ in R
R
remove.packages("rPython")
remove.packages("scLVM")
Sys.setenv(PATH = paste("/Users/arthur/Desktop/Dev/Anaconda/anaconda/bin", Sys.getenv("PATH"),sep=":"))
system("python --version")

> Python 2.7.12 :: Anaconda 4.0.0 (x86_64)

Sys.setenv(RPYTHON_PYTHON_VERSION = "2.7.12")
install.packages("rPython")
install.packages("/Users/arthur/Desktop/Dev/scLVM/R/scLVM_0.99.2.tar.gz")

> Error : .onAttach failed in attachNamespace() for 'scLVM', details:
>  call: if (pmatch("No module named ", e[[1]]) == 1) {
>  error: missing value where TRUE/FALSE needed
> Error: loading failed
> Execution halted
> ERROR: loading failed

It seems that R is still calling the "wrong" version of python:
library(rPython)
python.exec("import sys; print sys.version")

> 2.7.10 (default, Oct 23 2015, 19:19:21) 
> [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

system("python --version")

> Python 2.7.12 :: Anaconda 4.0.0 (x86_64)

Do you have any ideas?

Thanks,
Arthur

**Comment by lrodda** [comment]
@arthuryxt Did you make sure to restart your R after removing packages? Remove packages, export your 2.7.12 version and reopen R.
install.packages("rPython", type = "source")

check that right version installed

> library(rPython)
> python.exec("import sys; print sys.version")

should say 2.7.12

If you are using Rstudio make sure that sclvm is not just unchecked but completely uninstalled.

Then run in terminal
$ R CMD INSTALL scLVM_0.99.2.tar.gz

I hope this helps.

**Comment by arthuryxt** [comment]
@lrodda Thank you very much! Yet I still couldn't get it installed:

my commands are:

R
remove.packages("rPython")

> Removing package from ‘/Users/arthur/Library/R/3.3/library’
> Error in find.package(pkgs, lib) : there is no package called ‘rPython’

Sys.setenv(RPYTHON_PYTHON_VERSION = "2.7.12")
q()

export RPYTHON_PYTHON_VERSION=2.7.12

R
Sys.setenv(PATH = paste("/Users/arthur/Desktop/Dev/Anaconda/anaconda/bin", Sys.getenv("PATH"),sep=":"))
system("python --version")

> Python 2.7.12 :: Anaconda 4.0.0 (x86_64)

Sys.setenv(RPYTHON_PYTHON_VERSION = "2.7.12")
install.packages("rPython", type = "source")

> could not locate python2.7.12-config
> ERROR: configuration failed for package ‘rPython’
> *removing ‘/Users/arthur/Library/R/3.3/library/rPython’

Any suggestions please?

Best,
Arthur
